name:  CI/CD

on:
  push:
    branches:
      - main
      - dev
  pull_request:
  # Trigger the build step only when a new tag is created
  release:
    types: [created]

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.x'
          cache: 'npm'

      - name: Install npm packages
        run: npm ci

      - name: Lint with eslint
        run: npm run lint

      - name: Test with Jest
        run: npm run test:once